# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1341UcL1DTj5ciQnucQLW0TGbIM6t81qR
"""

!pip install streamlit

import streamlit as st

def find_largest(num1, num2, num3):
    return max(num1, num2, num3)

st.title('Find the Largest Number')
num1 = st.number_input('Enter the first number:', value=0)
num2 = st.number_input('Enter the second number:', value=0)
num3 = st.number_input('Enter the third number:', value=0)

if st.button('Find Largest'):
    largest_num = find_largest(num1, num2, num3)
    st.success(f'The largest number is: {largest_num}')